- source/compute-tuple-intersection.py:
    - description: Ensure that compute-tuple-intersection.py file exists in the source/ directory
      check: ConfirmFileExists
    - description: Complete all TODOs, remove the TODO markers, and rewrite comments for compute-tuple-intersection.py
      check: MatchFileFragment
      options:
        fragment: TODO
        count: 0
        exact: true
    - description: Create a sufficient number of docstring (i.e., multiple-line) comments in compute-tuple-intersection.py
      check: CountMultipleLineComments
      options:
        language: "Python"
        count: 1
        exact: false
    - description: Create a sufficient number of single-line comments in compute-tuple-intersection.py
      check: CountSingleLineComments
      options:
        language: "Python"
        count: 5
        exact: false

- source/perform-apply-to-each.py:
    - description: Ensure that perform-apply-to-each.py file exists in the source/ directory
      check: ConfirmFileExists
    - description: Complete all TODOs, remove the TODO markers, and rewrite comments for perform-apply-to-each.py
      check: MatchFileFragment
      options:
        fragment: TODO
        count: 0
        exact: true
    - description: Create a sufficient number of docstring (i.e., multiple-line) comments in perform-apply-to-each.py
      check: CountMultipleLineComments
      options:
        language: "Python"
        count: 1
        exact: false
    - description: Create a sufficient number of single-line comments in perform-apply-to-each.py
      check: CountSingleLineComments
      options:
        language: "Python"
        count: 5
        exact: false

# perform checks on a file
- writing/reflection.md:
    - description: Ensure that the reflection.md file exists in the writing/ directory
      check: ConfirmFileExists
    - description: Complete all TODOs, remove the TODO markers, and rewrite comments for reflection.md
      check: MatchFileFragment
      options:
        fragment: TODO
        count: 0
        exact: true
    - description: Delete the 'Add Your Name Here' prompt in the reflection file
      check: MatchFileFragment
      options:
        fragment: "Add Your Name Here"
        count: 0
        exact: true
    - description: Write a minimum number of meaningful words in the reflection
      check: CountFileWords
      options:
        count: 200
        exact: false
    - description: Confirm that the markdown file has the correct number of headers
      check: CountMarkdownTags
      options:
        tag: heading
        count: 11
        exact: false
    - description: Confirm that the markdown file has the correct number of fenced code blocks
      check: CountMarkdownTags
      options:
        tag: code_block
        count: 2
        exact: false

# run the program and confirm the existence of fragments in its output
- description: Run the compute-tuple-intersection program and confirm the correct number of non-blank lines in the output
  check: CountCommandOutput
  options:
    command: "python source/compute-tuple-intersection.py"
    count: 4
    exact: true

# run the program and confirm the existence of fragments in its output
- description: "Run the compute-tuple-intersection program and confirm the existence of content in its output"
  check: MatchCommandFragment
  options:
    command: "python source/compute-tuple-intersection.py"
    fragment: "The first tuple:"
    count: 1
    exact: true

# run the program and confirm the existence of fragments in its output
- description: "Run the compute-tuple-intersection program and confirm the existence of content in its output"
  check: MatchCommandFragment
  options:
    command: "python source/compute-tuple-intersection.py"
    fragment: "The second tuple:"
    count: 1
    exact: true

# run the program and confirm the existence of fragments in its output
- description: "Run the compute-tuple-intersection program and confirm the existence of content in its output"
  check: MatchCommandFragment
  options:
    command: "python source/compute-tuple-intersection.py"
    fragment: "('a', 2)"
    count: 1
    exact: true

# run the program and confirm the existence of fragments in its output
- description: "Run the compute-tuple-intersection program and confirm the existence of content in its output"
  check: MatchCommandFragment
  options:
    command: "python source/compute-tuple-intersection.py"
    fragment: "The first intersection tuple:"
    count: 1
    exact: true

# run the program and confirm the existence of fragments in its output
- description: Run the perform-apply-to-each program and confirm the correct number of non-blank lines in the output
  check: CountCommandOutput
  options:
    command: "python source/perform-apply-to-each.py"
    count: 4
    exact: true

# run the program and confirm the existence of fragments in its output
- description: "Run the perform-apply-to-each program and confirm the existence of content in its output"
  check: MatchCommandFragment
  options:
    command: "python source/perform-apply-to-each.py"
    fragment: "Values before transformations:"
    count: 1
    exact: true

# run the program and confirm the existence of fragments in its output
- description: "Run the perform-apply-to-each program and confirm the existence of content in its output"
  check: MatchCommandFragment
  options:
    command: "python source/perform-apply-to-each.py"
    fragment: "Values after applying abs:"
    count: 1
    exact: true

# run the program and confirm the existence of fragments in its output
- description: "Run the perform-apply-to-each program and confirm the existence of content in its output"
  check: MatchCommandFragment
  options:
    command: "python source/perform-apply-to-each.py"
    fragment: "Values after applying int:"
    count: 1
    exact: true

# run the program and confirm the existence of fragments in its output
- description: "Run the perform-apply-to-each program and confirm the existence of content in its output"
  check: MatchCommandFragment
  options:
    command: "python source/perform-apply-to-each.py"
    fragment: "Values after applying squaring:"
    count: 1
    exact: true

# confirm a suitable number of commit messages
- description: Have at least a specific minimum of commits in repository
  check: CountCommits
  options:
    count: 7
